### ISSUE TITLE
Failed to connect voice/video/screenshare call

### ISSUE THREAD

**Issue by chenyuz3** [fatwang2/dinopal#4]
![image](https://github.com/user-attachments/assets/78bc4199-d592-4799-992c-f66bd13c9ae3)
Hi guys, 

After the installation, I find myself unable to use any function in Dinopal, as it will show this error after I click start for any interaction

Not sure if this is becasue I am using a M4 pro Mac Mini which does not have a built-in camera.

Regards,
Jason

**Comment by fatwang2** [comment]
do you have microphone?

**Comment by chenyuz3** [comment]
> do you have microphone?

Yes, I do. I have a wired headset connected.

**Comment by fatwang2** [comment]
too many users just now, plz try it again

**Comment by chenyuz3** [comment]
> too many users just now, plz try it again

It works now!!
